#!/usr/bin/env python3
"""
Run Cellpose3-cyto3 on a large image using tiled processing.

The script splits a large input image into overlapping tiles, runs Cellpose
on each tile, and merges the tile-level masks into a single full-size mask.

Large input images and output masks are not included in this repository.
Please provide local input and output paths when running the script.
"""

import argparse
import os
import subprocess
from pathlib import Path

import numpy as np
import tifffile as tiff


def parse_args():
    parser = argparse.ArgumentParser(
        description="Run tiled Cellpose3-cyto3 segmentation on a large image."
    )
    parser.add_argument(
        "--image",
        required=True,
        help="Path to the input tif/tiff image.",
    )
    parser.add_argument(
        "--output-root",
        required=True,
        help="Root directory for tile images, tile outputs, merged mask, and logs.",
    )
    parser.add_argument(
        "--gpu-id",
        default="0",
        help="GPU ID to use. Default: 0.",
    )
    parser.add_argument(
        "--tile-size",
        type=int,
        default=4096,
        help="Tile size in pixels. Default: 4096.",
    )
    parser.add_argument(
        "--overlap",
        type=int,
        default=256,
        help="Overlap size between neighboring tiles in pixels. Default: 256.",
    )
    parser.add_argument(
        "--cpu-threads",
        type=str,
        default="20",
        help="Number of CPU threads for numerical libraries. Default: 20.",
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Re-run tiles even if tile-level mask outputs already exist.",
    )
    return parser.parse_args()


def ensure_dirs(directories):
    for directory in directories:
        directory.mkdir(parents=True, exist_ok=True)


def get_2d_shape(img: np.ndarray):
    """Return image height and width for 2D, HWC, or CHW images."""
    if img.ndim == 2:
        return img.shape[0], img.shape[1]

    if img.ndim == 3:
        if img.shape[-1] <= 10:  # HWC
            return img.shape[0], img.shape[1]
        if img.shape[0] <= 10:  # CHW
            return img.shape[1], img.shape[2]

    raise ValueError(f"Unsupported image shape: {img.shape}")


def crop_image(img: np.ndarray, y0: int, y1: int, x0: int, x1: int):
    """Crop a tile from a 2D, HWC, or CHW image."""
    if img.ndim == 2:
        return img[y0:y1, x0:x1]

    if img.ndim == 3:
        if img.shape[-1] <= 10:  # HWC
            return img[y0:y1, x0:x1, :]
        if img.shape[0] <= 10:  # CHW
            return img[:, y0:y1, x0:x1]

    raise ValueError(f"Unsupported image shape: {img.shape}")


def generate_tiles(height: int, width: int, tile_size: int, overlap: int):
    """Generate tile coordinates as (y0, y1, x0, x1)."""
    step = tile_size - overlap
    if step <= 0:
        raise ValueError("tile_size must be larger than overlap.")

    ys = list(range(0, max(height - tile_size, 0) + 1, step))
    xs = list(range(0, max(width - tile_size, 0) + 1, step))

    if height <= tile_size:
        ys = [0]
    elif ys[-1] != height - tile_size:
        ys.append(height - tile_size)

    if width <= tile_size:
        xs = [0]
    elif xs[-1] != width - tile_size:
        xs.append(width - tile_size)

    for y0 in ys:
        for x0 in xs:
            y1 = min(y0 + tile_size, height)
            x1 = min(x0 + tile_size, width)
            yield y0, y1, x0, x1


def find_mask_file(tile_out_dir: Path):
    """Find the mask file generated by Cellpose for a tile."""
    candidates = list(tile_out_dir.glob("*_masks.tif")) + list(tile_out_dir.glob("*_masks.tiff"))
    if candidates:
        return candidates[0]

    candidates = list(tile_out_dir.glob("*masks*.tif")) + list(tile_out_dir.glob("*masks*.tiff"))
    if candidates:
        return candidates[0]

    return None


def run_cellpose_on_tile(
    tile_path: Path,
    out_dir: Path,
    log_path: Path,
    model_name: str,
    gpu_id: str,
    cpu_threads: str,
):
    """Run Cellpose on a single tile."""
    out_dir.mkdir(parents=True, exist_ok=True)

    cmd = [
        "python",
        "-m",
        "cellpose",
        "--image_path",
        str(tile_path),
        "--pretrained_model",
        model_name,
        "--use_gpu",
        "--save_tif",
        "--savedir",
        str(out_dir),
        "--verbose",
    ]

    env = os.environ.copy()
    env["CUDA_VISIBLE_DEVICES"] = gpu_id
    env["OMP_NUM_THREADS"] = cpu_threads
    env["MKL_NUM_THREADS"] = cpu_threads
    env["OPENBLAS_NUM_THREADS"] = cpu_threads
    env["NUMEXPR_NUM_THREADS"] = cpu_threads

    with open(log_path, "w") as f:
        f.write("Command:\n")
        f.write(" ".join(cmd) + "\n\n")
        f.write(f"CUDA_VISIBLE_DEVICES={gpu_id}\n")
        f.write(f"MODEL_NAME={model_name}\n\n")

        result = subprocess.run(
            cmd,
            stdout=f,
            stderr=subprocess.STDOUT,
            env=env,
            check=False,
        )

    return result.returncode


def paste_mask_nonoverlap(
    merged_mask: np.ndarray,
    tile_mask: np.ndarray,
    y0: int,
    y1: int,
    x0: int,
    x1: int,
    height: int,
    width: int,
    label_offset: int,
    overlap: int,
):
    """
    Paste only the central non-overlapping region of each tile.

    Labels are reassigned to keep cell IDs unique across tiles.
    """
    tile_h, tile_w = tile_mask.shape[:2]

    top_cut = overlap // 2 if y0 > 0 else 0
    left_cut = overlap // 2 if x0 > 0 else 0
    bottom_cut = overlap // 2 if y1 < height else 0
    right_cut = overlap // 2 if x1 < width else 0

    ty0 = top_cut
    ty1 = tile_h - bottom_cut
    tx0 = left_cut
    tx1 = tile_w - right_cut

    gy0 = y0 + ty0
    gy1 = y0 + ty1
    gx0 = x0 + tx0
    gx1 = x0 + tx1

    valid_mask = tile_mask[ty0:ty1, tx0:tx1].copy()

    if valid_mask.size == 0:
        return label_offset

    labels = np.unique(valid_mask)
    labels = labels[labels > 0]

    if len(labels) == 0:
        return label_offset

    relabeled = np.zeros_like(valid_mask, dtype=np.uint32)

    for label in labels:
        label_offset += 1
        relabeled[valid_mask == label] = label_offset

    target = merged_mask[gy0:gy1, gx0:gx1]
    paste_region = (relabeled > 0) & (target == 0)
    target[paste_region] = relabeled[paste_region]
    merged_mask[gy0:gy1, gx0:gx1] = target

    return label_offset


def main():
    args = parse_args()

    image_path = Path(args.image)
    output_root = Path(args.output_root)
    model_name = "cyto3"

    tile_img_dir = output_root / "tiles_img"
    tile_out_dir = output_root / "tiles_out"
    merged_dir = output_root / "merged"
    log_dir = output_root / "logs"

    ensure_dirs([output_root, tile_img_dir, tile_out_dir, merged_dir, log_dir])

    print("========================================")
    print("Tile-based Cellpose3-cyto3 run")
    print(f"Image: {image_path}")
    print(f"Model: {model_name}")
    print(f"GPU ID: {args.gpu_id}")
    print(f"Tile size: {args.tile_size}")
    print(f"Overlap: {args.overlap}")
    print(f"Output root: {output_root}")
    print("========================================")

    if not image_path.exists():
        raise FileNotFoundError(f"Image not found: {image_path}")

    img = tiff.imread(image_path)
    height, width = get_2d_shape(img)

    print(f"Image shape: {img.shape}")
    print(f"2D size: H={height}, W={width}")

    merged_mask = np.zeros((height, width), dtype=np.uint32)
    label_offset = 0

    tiles = list(generate_tiles(height, width, args.tile_size, args.overlap))
    print(f"Total tiles: {len(tiles)}")

    summary_log = log_dir / f"{image_path.stem}_tile_summary.log"

    with open(summary_log, "w") as sf:
        sf.write(f"Image: {image_path}\n")
        sf.write(f"Shape: {img.shape}\n")
        sf.write(f"Model: {model_name}\n")
        sf.write(f"GPU ID: {args.gpu_id}\n")
        sf.write(f"Tile size: {args.tile_size}\n")
        sf.write(f"Overlap: {args.overlap}\n")
        sf.write(f"Total tiles: {len(tiles)}\n\n")

    for idx, (y0, y1, x0, x1) in enumerate(tiles, start=1):
        tile_name = f"{image_path.stem}_tile{idx:04d}_y{y0}_{y1}_x{x0}_{x1}.tif"
        tile_path = tile_img_dir / tile_name
        tile_stem = tile_path.stem
        out_dir = tile_out_dir / tile_stem
        log_path = log_dir / f"{tile_stem}.log"

        print(f"[{idx}/{len(tiles)}] tile y={y0}:{y1}, x={x0}:{x1}")

        mask_file = find_mask_file(out_dir)

        if mask_file is not None and not args.overwrite:
            print(f"  Skip existing tile result: {mask_file}")
        else:
            tile_img = crop_image(img, y0, y1, x0, x1)
            tiff.imwrite(tile_path, tile_img)

            exit_code = run_cellpose_on_tile(
                tile_path=tile_path,
                out_dir=out_dir,
                log_path=log_path,
                model_name=model_name,
                gpu_id=args.gpu_id,
                cpu_threads=args.cpu_threads,
            )

            with open(summary_log, "a") as sf:
                sf.write(
                    f"Tile {idx}: y={y0}:{y1}, x={x0}:{x1}, exit_code={exit_code}\n"
                )
                sf.write(f"  tile_path={tile_path}\n")
                sf.write(f"  log_path={log_path}\n")

            if exit_code != 0:
                print(f"  FAILED tile {idx}, check log: {log_path}")
                continue

            mask_file = find_mask_file(out_dir)

        if mask_file is None:
            print(f"  No mask found for tile {idx}, skip merge.")
            continue

        tile_mask = tiff.imread(mask_file)

        if tile_mask.ndim != 2:
            raise ValueError(f"Mask is not 2D: {mask_file}, shape={tile_mask.shape}")

        label_offset = paste_mask_nonoverlap(
            merged_mask=merged_mask,
            tile_mask=tile_mask,
            y0=y0,
            y1=y1,
            x0=x0,
            x1=x1,
            height=height,
            width=width,
            label_offset=label_offset,
            overlap=args.overlap,
        )

        print(f"  Merged. Current max label: {label_offset}")

    merged_path = merged_dir / f"{image_path.stem}_cellpose3_{model_name}_tile_merged_mask.tif"
    print(f"Saving merged mask: {merged_path}")
    tiff.imwrite(merged_path, merged_mask, compression="zlib")

    print("========================================")
    print("Done.")
    print(f"Merged mask: {merged_path}")
    print(f"Summary log: {summary_log}")
    print(f"Final max label: {int(merged_mask.max())}")
    print("========================================")


if __name__ == "__main__":
    main()
