name: cellbin2-st
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - affine=2.4.0
  - asttokens=3.0.0
  - aws-c-auth=0.9.0
  - aws-c-cal=0.9.2
  - aws-c-common=0.12.3
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.5
  - aws-c-http=0.10.2
  - aws-c-io=0.20.1
  - aws-c-mqtt=0.13.1
  - aws-c-s3=0.8.3
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.32.10
  - aws-sdk-cpp=1.11.510
  - azure-core-cpp=1.10.3
  - azure-identity-cpp=1.6.0
  - azure-storage-blobs-cpp=12.10.0
  - azure-storage-common-cpp=12.5.0
  - backcall=0.2.0
  - binutils=2.44
  - binutils_impl_linux-64=2.44
  - binutils_linux-64=2.44
  - blas=2.306
  - blas-devel=3.11.0
  - blosc=1.21.6
  - boost-cpp=1.78.0
  - branca=0.7.2
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.34.6
  - c-compiler=1.11.0
  - ca-certificates=2026.2.25
  - cairo=1.16.0
  - capnproto=0.9.1
  - cfitsio=4.2.0
  - click-plugins=1.1.1
  - cligj=0.7.2
  - comm=0.2.2
  - conda-gcc-specs=14.3.0
  - contourpy=1.1.1
  - curl=8.16.0
  - cxx-compiler=1.11.0
  - cycler=0.12.1
  - cyrus-sasl=2.1.27
  - debugpy=1.8.5
  - decorator=5.1.1
  - executing=2.1.0
  - fiona=1.9.4
  - fmt=11.0.2
  - folium=0.18.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.17.1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.14.2
  - freexl=1.0.6
  - gcc=14.3.0
  - gcc_impl_linux-64=14.3.0
  - gcc_linux-64=14.3.0
  - gdal=3.7.0
  - geopandas=0.13.2
  - geopandas-base=0.13.2
  - geos=3.11.2
  - geotiff=1.7.1
  - gettext=0.25.1
  - gettext-tools=0.25.1
  - giflib=5.2.2
  - gxx=14.3.0
  - gxx_impl_linux-64=14.3.0
  - gxx_linux-64=14.3.0
  - h2=4.1.0
  - hdf4=4.2.15
  - hdf5=1.14.0
  - hpack=4.0.0
  - hyperframe=6.0.1
  - icu=72.1
  - importlib-metadata=8.5.0
  - importlib-resources=6.4.5
  - importlib_resources=6.4.5
  - ipykernel=6.29.5
  - ipython=8.12.2
  - jedi=0.19.1
  - joblib=1.4.2
  - json-c=0.16
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - kealib=1.5.1
  - kernel-headers_linux-64=5.14.0
  - keyutils=1.6.3
  - krb5=1.21.2
  - lcms2=2.15
  - ld_impl_linux-64=2.44
  - lerc=4.1.0
  - libabseil=20240722.0
  - libaec=1.1.5
  - libarchive=3.6.2
  - libasprintf=0.25.1
  - libasprintf-devel=0.25.1
  - libblas=3.11.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.11.0
  - libcrc32c=1.1.2
  - libcurl=8.16.0
  - libdeflate=1.18
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.5
  - libffi=3.4.4
  - libfreetype=2.14.2
  - libfreetype6=2.14.2
  - libgcc=15.2.0
  - libgcc-devel_linux-64=14.3.0
  - libgcc-ng=15.2.0
  - libgdal=3.7.0
  - libgettextpo=0.25.1
  - libgettextpo-devel=0.25.1
  - libgfortran=15.2.0
  - libgfortran-ng=15.2.0
  - libgfortran5=15.2.0
  - libglib=2.78.1
  - libgomp=15.2.0
  - libiconv=1.18
  - libidn2=2.3.8
  - libjpeg-turbo=2.1.5.1
  - libkml=1.3.0
  - liblapack=3.11.0
  - liblapacke=3.11.0
  - liblzma=5.8.2
  - libnetcdf=4.9.2
  - libnghttp2=1.58.0
  - libnsl=2.0.1
  - libntlm=1.8
  - libopenblas=0.3.32
  - libpng=1.6.55
  - libpq=15.4
  - libprotobuf=5.28.2
  - libre2-11=2024.07.02
  - librttopo=1.1.0
  - libsanitizer=14.3.0
  - libsodium=1.0.18
  - libspatialindex=2.0.0
  - libspatialite=5.0.1
  - libsqlite=3.52.0
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-devel_linux-64=14.3.0
  - libstdcxx-ng=15.2.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libuuid=2.41.3
  - libwebp-base=1.6.0
  - libxcb=1.15
  - libxcrypt=4.4.36
  - libxml2=2.11.5
  - libxslt=1.1.37
  - libzip=1.10.1
  - libzlib=1.3.1
  - lz4-c=1.9.4
  - lzo=2.10
  - mapclassify=2.5.0
  - markupsafe=2.1.5
  - matplotlib-base=3.7.3
  - matplotlib-inline=0.1.7
  - minizip=4.0.3
  - munch=4.0.0
  - munkres=1.1.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.1
  - nspr=4.38
  - nss=3.118
  - openblas=0.3.32
  - openjpeg=2.5.0
  - openldap=2.6.6
  - openssl=3.1.8
  - packaging=26.0
  - parso=0.8.4
  - pcre2=10.40
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=24.2
  - pixman=0.46.4
  - platformdirs=4.3.6
  - pooch=1.8.2
  - poppler=23.05.0
  - poppler-data=0.4.12
  - postgresql=15.4
  - proj=9.2.0
  - prompt-toolkit=3.0.48
  - prompt_toolkit=3.0.48
  - psutil=6.0.0
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.18.0
  - pyparsing=3.1.4
  - pyproj=3.5.0
  - pysocks=1.7.1
  - python=3.8.20
  - python-tzdata=2024.2
  - python_abi=3.8
  - pyzmq=26.2.0
  - rasterio=1.3.7
  - re2=2024.07.02
  - readline=8.3
  - rtree=1.3.0
  - s2n=1.5.14
  - snappy=1.2.2
  - snuggs=1.4.7
  - spdlog=1.14.1
  - sqlite=3.51.2
  - stack_data=0.6.2
  - sysroot_linux-64=2.34
  - threadpoolctl=3.5.0
  - tiledb=2.13.2
  - tk=8.6.14
  - tornado=6.4.1
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - tzcode=2026a
  - tzdata=2025c
  - unicodedata2=15.1.0
  - uriparser=0.9.8
  - wheel=0.44.0
  - xerces-c=3.2.4
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.9
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.11
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xorgproto=2025.1
  - xorg-xproto=7.0.31
  - xyzservices=2025.11.0
  - xz=5.8.2
  - zeromq=4.3.5
  - zlib=1.3.1
  - zstandard=0.19.0
  - zstd=1.5.7
  - pip:
      - aenum==3.1.17
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.10.11
      - aiosignal==1.3.1
      - alabaster==0.7.13
      - anndata==0.9.2
      - annotated-types==0.7.0
      - arboreto==0.1.6
      - asciitree==0.3.3
      - async-timeout==5.0.1
      - attrs==25.3.0
      - babel==2.18.0
      - beautifulsoup4==4.14.3
      - biopython==1.83
      - bleach==6.1.0
      - bokeh==2.4.3
      - boltons==25.0.0
      - cell-bin==1.3.4.1
      - cellbin2==1.2.1
      - cellpose==3.0.11
      - certifi==2026.2.25
      - cffi==1.17.1
      - charset-normalizer==3.4.6
      - click==8.1.8
      - cloudpickle==3.1.2
      - colorcet==3.1.0
      - coloredlogs==15.0.1
      - cramjam==2.11.0
      - csscompressor==0.9.5
      - ctxcore==0.2.0
      - cython==3.2.4
      - cytoolz==1.0.1
      - dask==2023.5.0
      - dask-image==2023.3.0
      - datashader==0.15.2
      - datashape==0.5.2
      - dill==0.4.0
      - distinctipy==1.3.4
      - distributed==2023.5.0
      - docrep==0.3.2
      - docutils==0.20.1
      - fastcluster==1.2.6
      - fasteners==0.20
      - fastparquet==2024.2.0
      - fastremap==1.15.1
      - fbpca==1.0
      - filelock==3.16.1
      - flatbuffers==25.12.19
      - fonttools==4.57.0
      - frozendict==2.4.7
      - frozenlist==1.5.0
      - fsspec==2025.3.0
      - gefpy==1.2.6
      - geojson==3.2.0
      - geosketch==1.3
      - get-annotations==0.1.2
      - gtfparse==1.2.1
      - h5py==3.8.0
      - harmonypy==0.0.6
      - holoviews==1.17.1
      - hotspotsc==1.1.1
      - humanfriendly==10.0
      - hvplot==0.10.0
      - idna==3.11
      - igraph==0.11.8
      - imagecodecs==2023.3.16
      - imageio==2.31.1
      - imagesize==1.5.0
      - imreg-dft==2.0.0
      - inflect==7.4.0
      - interlap==0.2.7
      - jinja2==3.1.6
      - jsmin==3.0.1
      - kdepy==1.1.0
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - leidenalg==0.10.2
      - llvmlite==0.39.1
      - locket==1.0.0
      - loompy==3.0.6
      - louvain==0.8.2
      - lxml==6.0.2
      - lz4==4.3.3
      - mapbox-earcut==1.0.1
      - markdown==3.7
      - matplotlib==3.7.1
      - matplotlib-scalebar==0.8.1
      - more-itertools==10.5.0
      - mpmath==1.3.0
      - msgpack==1.1.1
      - multidict==6.1.0
      - multipledispatch==1.0.0
      - multiprocessing-on-dill==3.5.0a4
      - narwhals==1.42.1
      - natsort==7.1.1
      - numba==0.56.4
      - numcodecs==0.12.1
      - numexpr==2.8.6
      - numpy==1.23.5
      - numpy-groupies==0.9.22
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu11==9.1.0.70
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-nccl-cu11==2.20.5
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvtx-cu11==11.8.86
      - nvidia-nvtx-cu12==12.1.105
      - objtyping==0.5.4
      - omnipath==1.0.8
      - onnxruntime==1.15.1
      - onnxruntime-gpu==1.15.1
      - opencv-python==4.8.0.76
      - opencv-python-headless==4.13.0.92
      - pandas==1.5.3
      - panel==0.14.4
      - param==1.13.0
      - partd==1.4.1
      - patchify==0.2.3
      - patsy==0.5.6
      - phenograph==1.5.7
      - pillow==10.4.0
      - pims==0.7
      - pkgconfig==1.5.5
      - plotly==6.6.0
      - pot==0.9.1
      - prettytable==3.11.0
      - propcache==0.2.0
      - protobuf==5.29.6
      - pyarrow==17.0.0
      - pycirclize==1.6.0
      - pycparser==2.23
      - pyct==0.6.0
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pynndescent==0.6.0
      - pypdf2==3.0.1
      - pyscenic==0.12.1
      - python-dateutil==2.9.0.post0
      - pytz==2026.1.post1
      - pyvips==2.2.1
      - pyvips-binary==8.18.1
      - pyviz-comms==3.0.6
      - pywavelets==1.4.1
      - pyyaml==6.0.3
      - reportlab==4.4.3
      - requests==2.32.4
      - retrying==1.4.2
      - roifile==2023.5.12
      - scanpy==1.9.6
      - scikit-image==0.21.0
      - scikit-learn==1.3.0
      - scipy==1.10.1
      - seaborn==0.12.2
      - session-info==1.0.1
      - setuptools==69.5.1
      - shapely==2.0.7
      - six==1.17.0
      - slicerator==1.1.0
      - slideio==2.8.0
      - snowballstemmer==3.0.1
      - sortedcontainers==2.4.0
      - soupsieve==2.7
      - spatialpandas==0.4.9
      - sphinx==7.1.2
      - sphinxcontrib-applehelp==1.0.4
      - sphinxcontrib-devhelp==1.0.2
      - sphinxcontrib-htmlhelp==2.0.1
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==1.0.3
      - sphinxcontrib-serializinghtml==1.1.5
      - sqlalchemy==1.3.24
      - squidpy==1.2.2
      - statsmodels==0.14.1
      - stdlib-list==0.10.0
      - stereo==0.1.2
      - stereopy==1.6.0
      - sympy==1.13.3
      - tblib==3.0.0
      - texttable==1.7.0
      - tifffile==2023.2.3
      - toolz==1.0.0
      - torch==2.4.1+cu118
      - torchaudio==2.4.1+cu118
      - torchvision==0.19.1+cu118
      - tqdm==4.65.0
      - triton==3.0.0
      - typeguard==4.4.0
      - typing-extensions==4.13.2
      - umap-learn==0.5.1
      - urllib3==2.1.0
      - validators==0.34.0
      - wcwidth==0.6.0
      - webencodings==0.5.1
      - wrapt==2.0.1
      - xarray==0.20.1
      - yarl==1.15.2
      - zarr==2.16.1
      - zict==3.0.0
      - zipp==3.20.2
