name: spateo
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - anyio=4.10.0
  - argon2-cffi=25.1.0
  - argon2-cffi-bindings=25.1.0
  - arrow=1.3.0
  - arrow-cpp=21.0.0
  - async-lru=2.0.5
  - aws-c-auth=0.9.0
  - aws-c-cal=0.9.2
  - aws-c-common=0.12.4
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.6
  - aws-c-http=0.10.4
  - aws-c-io=0.21.4
  - aws-c-mqtt=0.13.3
  - aws-c-s3=0.8.7
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.34.0
  - aws-sdk-cpp=1.11.638
  - babel=2.17.0
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.34.6
  - ca-certificates=2026.3.19
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cffi=1.17.1
  - comm=0.2.3
  - debugpy=1.8.16
  - decorator=5.2.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - expat=2.7.5
  - fqdn=1.5.1
  - gettext=0.25.1
  - gettext-tools=0.25.1
  - gflags=2.2.2
  - glog=0.5.0
  - h11=0.16.0
  - h2=4.2.0
  - hpack=4.1.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - hyperframe=6.1.0
  - icu=73.1
  - ipykernel=6.29.5
  - ipython=8.18.1
  - isoduration=20.11.0
  - jansson=2.14
  - jedi=0.19.2
  - jinja2=3.1.6
  - json5=0.12.1
  - jsonpointer=3.0.0
  - jsonschema=4.25.1
  - jsonschema-with-format-nongpl=4.25.1
  - jupyter-lsp=2.2.6
  - jupyter_client=7.4.9
  - jupyter_core=5.8.1
  - jupyter_events=0.12.0
  - jupyter_server=2.16.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.4.6
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - keyutils=1.6.3
  - krb5=1.21.3
  - lark=1.2.2
  - ld_impl_linux-64=2.44
  - libabseil=20250814.1
  - libasprintf=0.25.1
  - libasprintf-devel=0.25.1
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcurl=8.19.0
  - libedit=3.1.20250104
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.5
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgettextpo=0.25.1
  - libgettextpo-devel=0.25.1
  - libgomp=15.2.0
  - libgrpc=1.74.1
  - libiconv=1.18
  - libidn2=2.3.8
  - libkrb5=1.22.1
  - libnghttp2=1.67.1
  - libnsl=2.0.0
  - libprotobuf=6.33.0
  - libre2-11=2025.11.05
  - libsodium=1.0.20
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libthrift=0.22.0
  - libunistring=1.3
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libxml2=2.13.9
  - libzlib=1.3.1
  - lmdb=0.9.31
  - lz4-c=1.9.4
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - notebook=7.4.5
  - notebook-shim=0.2.4
  - openssl=3.6.1
  - orc=2.2.0
  - overrides=7.7.0
  - packaging=26.0
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=26.0.1
  - prometheus_client=0.22.1
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pyarrow=21.0.0
  - pycparser=2.22
  - pysocks=1.7.1
  - python=3.9.25
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.2
  - python-json-logger=2.0.7
  - python_abi=3.9
  - re2=2025.11.05
  - readline=8.3
  - referencing=0.36.2
  - requests=2.32.5
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rfc3987-syntax=1.1.0
  - s2n=1.5.14
  - send2trash=1.8.3
  - setuptools=80.9.0
  - six=1.17.0
  - snappy=1.2.2
  - sniffio=1.3.1
  - sqlite=3.51.2
  - stack_data=0.6.3
  - terminado=0.18.1
  - tinycss2=1.4.0
  - tk=8.6.15
  - tomli=2.2.1
  - traitlets=5.14.3
  - types-python-dateutil=2.9.0.20250809
  - typing_extensions=4.14.1
  - typing_utils=0.1.0
  - uri-template=1.3.0
  - utf8proc=2.6.1
  - webcolors=24.11.1
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.8.2
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.7
  - pip:
      - absl-py==2.3.1
      - access==1.1.9
      - adjusttext==1.3.0
      - affine==2.4.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.5
      - aiosignal==1.4.0
      - anndata==0.10.9
      - appdirs==1.4.4
      - array-api-compat==1.11.2
      - asttokens==3.0.1
      - astunparse==1.6.3
      - async-timeout==5.0.1
      - attrs==26.1.0
      - beautifulsoup4==4.14.3
      - branca==0.8.2
      - certifi==2026.2.25
      - cfgv==3.4.0
      - charset-normalizer==3.4.6
      - click==8.1.8
      - click-plugins==1.1.1.2
      - cligj==0.7.2
      - colorcet==3.1.0
      - contourpy==1.3.0
      - csbdeep==0.8.2
      - cycler==0.12.1
      - datacache==1.4.1
      - deprecation==2.1.0
      - descartes==1.1.0
      - distlib==0.4.0
      - dunamai==1.26.0
      - dynamo-release==1.5.3
      - esda==2.5.1
      - et-xmlfile==2.0.0
      - exceptiongroup==1.3.1
      - executing==2.2.1
      - filelock==3.19.1
      - fiona==1.10.1
      - flatbuffers==25.12.19
      - folium==0.20.0
      - fonttools==4.60.2
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - gast==0.7.0
      - geopandas==1.0.1
      - get-annotations==0.1.2
      - get-version==3.5.5
      - giddy==2.3.5
      - google-pasta==0.2.0
      - gpytorch==1.13
      - grpcio==1.80.0
      - h5py==3.14.0
      - identify==2.6.15
      - idna==3.11
      - igraph==1.0.0
      - imageio==2.37.2
      - importlib-metadata==8.7.1
      - importlib-resources==6.5.2
      - inequality==1.0.0
      - ipywidgets==8.1.8
      - jaxtyping==0.2.19
      - joblib==1.5.3
      - jsonschema-specifications==2025.9.1
      - jupyterlab-widgets==3.0.16
      - keras==3.10.0
      - kiwisolver==1.4.7
      - kneed==0.8.6
      - kornia==0.8.2
      - kornia-rs==0.1.10
      - lazy-loader==0.5
      - legacy-api-wrap==1.5
      - leidenalg==0.11.0
      - libclang==18.1.1
      - libpysal==4.8.1
      - linear-operator==0.5.3
      - llvmlite==0.43.0
      - loompy==3.0.8
      - mapclassify==2.8.1
      - markdown==3.9
      - markdown-it-py==3.0.0
      - markupsafe==3.0.3
      - matplotlib==3.9.4
      - matplotlib-inline==0.2.1
      - mdurl==0.1.2
      - mgwr==2.2.1
      - mistune==3.2.0
      - ml-dtypes==0.5.4
      - mock==5.2.0
      - momepy==0.6.0
      - more-itertools==10.8.0
      - mpmath==1.3.0
      - msgpack==1.1.2
      - mudata==0.2.4
      - multidict==6.7.1
      - namex==0.1.0
      - narwhals==2.18.1
      - natsort==8.4.0
      - nbclient==0.10.2
      - nbconvert==7.17.0
      - networkx==3.2.1
      - nodeenv==1.10.0
      - numba==0.60.0
      - numdifftools==0.9.41
      - numpy==2.0.2
      - numpy-groupies==0.11.3
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu12==12.8.90
      - opencv-python==4.13.0.92
      - openpyxl==3.1.5
      - opt-einsum==3.4.0
      - optree==0.19.0
      - pandas==2.3.3
      - pandocfilters==1.5.1
      - parso==0.8.6
      - patsy==1.0.2
      - pillow==11.3.0
      - platformdirs==4.4.0
      - plotly==6.6.0
      - pointpats==2.4.0
      - pooch==1.9.0
      - pot==0.9.6.post1
      - pre-commit==4.3.0
      - progressbar33==2.4
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - protobuf==6.33.6
      - psutil==7.2.2
      - pulp==3.3.0
      - pygments==2.20.0
      - pynndescent==0.6.0
      - pyogrio==0.11.1
      - pyparsing==3.3.2
      - pyproj==3.6.1
      - pyro-api==0.1.2
      - pyro-ppl==1.9.1
      - pysal==24.1
      - python-discovery==1.2.1
      - python-igraph==1.0.0
      - pytz==2026.1.post1
      - pyvista==0.46.5
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - quantecon==0.11.1
      - rasterio==1.4.3
      - rasterstats==0.20.0
      - rich==14.3.3
      - rpds-py==0.27.1
      - rtree==1.4.1
      - scanpy==1.10.3
      - scikit-image==0.24.0
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - scooby==0.11.0
      - seaborn==0.13.2
      - segregation==2.5.4
      - session-info==1.0.1
      - shapely==2.0.7
      - simplejson==3.20.2
      - soupsieve==2.8.3
      - spaghetti==1.7.4
      - spateo-release==1.1.1
      - spglm==1.1.0
      - spint==1.0.7
      - splot==1.1.7
      - spopt==0.5.0
      - spreg==1.9.0
      - spvcm==0.3.0
      - stardist==0.9.2
      - statsmodels==0.14.6
      - stdlib-list==0.12.0
      - sympy==1.14.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.20.0
      - termcolor==3.1.0
      - texttable==1.7.0
      - threadpoolctl==3.6.0
      - tifffile==2024.8.30
      - tobler==0.12.1
      - torch==2.8.0
      - tornado==6.5.5
      - tqdm==4.67.3
      - trame==3.12.0
      - trame-client==3.11.4
      - trame-common==1.1.3
      - trame-server==3.10.0
      - triton==3.4.0
      - typechecks==0.1.0
      - typeguard==4.5.1
      - typing-extensions==4.15.0
      - tzdata==2025.3
      - umap-learn==0.5.11
      - urllib3==2.6.3
      - virtualenv==21.2.0
      - vtk==9.5.2
      - wcwidth==0.6.0
      - werkzeug==3.1.8
      - widgetsnbextension==4.0.15
      - wrapt==2.1.2
      - wslink==2.5.0
      - xyzservices==2026.3.0
      - yarl==1.22.0
